version: '2'
services:
  influxdb:
    image: "tutum/influxdb"
    environment:
     - PRE_CREATE_DB=wadus
    ports:
     - "8083:8083"
     - "8086:8086"
     - "8090:8090"
     - "8099:8099"
  grafana:
    image: "grafana/grafana"
    ports:
     - "3000:3000"
