# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/stretch64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = "4096"
  end
  #

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     sudo cp /vagrant/sources.list /etc/apt
     echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
     sudo apt-get -y remove dictionaries-common
     sudo apt-get update
     sudo /usr/share/debconf/fix_db.pl # fix for dictionaries-common bug
     sudo apt-get install -y build-essential module-assistant
     sudo apt-get install -y virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
     # sudo apt-get install -y xfce4 xfce4-goodies
     # sudo apt-get install gnome-icon-theme-full tango-icon-theme
     sudo apt-get install -y apache2
     sudo apt-get install -y task-kde-desktop
     sudo cp /vagrant/Xwrapper.config /etc/X11
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    # Fix dictionaries-common
    # /usr/share/debconf/fix_db.pl
    # sudo apt-get -y upgrade
    # sudo apt-get -y install build-essential git iceweasel
    # sudo apt-get -y install xserver-xorg-legacy
    echo "Hola!"
  SHELL

end
