# Run Docker containers from Vagrant
#

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 8087

  config.vm.synced_folder "dfiles", "/opt/dfiles"
  config.vm.synced_folder "var", "/opt/var"

  config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
      # name
      vb.name = "docker-home"
   end

   config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.provision "shell", inline: <<-SHELL
    #sed -i 's/^mesg n$/tty -s \&\& mesg n/g' /root/.profile
    sudo mkdir -p /opt/config || /bin/true
    sudo mkdir -p /opt/dfiles || /bin/true
    sudo apt-get -y update
    sudo apt-get -y dist-upgrade
  SHELL

  config.vm.provision "docker" do |d|
    d.pull_images "ubuntu:16.04"
    # d.pull_images "ubuntu:15.04"
  end

  config.vm.provision "shell", inline: <<-SHELL
	echo "Provisioning completed!"
  SHELL

end
